print_ip: 04-print_ip/print_ip.h File Reference
print_ip.h File Reference
Classes
struct is_tuple_of_same_types_< H, T >
struct is_tuple_of_same_types_< Head, std::tuple<> >
struct is_tuple_of_same_types_< A, std::tuple< Head, Tail... > >
struct is_tuple_of_same_types< T >
struct is_tuple_of_same_types< std::tuple< H, T... > >
struct is_tuple_of_same_types< std::tuple<> >
Functions
template<typename T >
requires (std::integral< T >) std
template<typename T >
requires (std::is_convertible_v< T, std::string_view >) std
template<typename T >
requires (is_vector< T >||is_list< T >) std
template<size_t i, typename... T>
std::string tuple_print (const std::tuple< T... > &t)
template<typename T >
std::string to_string (T t) requires is_tup< T >
template<typename T >
void print_ip (T t)
Print ip to std::cout.
Variables
template<typename T >
concept is_vector = std::same_as<std::decay_t<T>, std::vector<typename std::decay_t<T>::value_type> >
Check T is std::vector.
template<typename T >
concept is_list = std::same_as<std::decay_t<T>, std::list<typename std::decay_t<T>::value_type> >
Check T is std::list.
template<typename T >
concept is_tup = is_tuple_of_same_types<T>::value
Check T is std::tuple with one type elements.
Detailed Description
print_ip.h
Definition in file print_ip.h.
Function Documentation
print_ip()
template<typename T > void print_ip (T t)
Print ip to std::cout.
Template Parameters
T template parameter, should be integer type or std::string/vector/list/tuple from the same type elements
Parameters
t printing value Example using
print_ip(std::make_tuple(123, 456, 789, 0, 222));
Definition at line 134 of file print_ip.h.
                    {  // Обернул вызов to_string - чтобы делать модульное тестирование над ним
     std::cout << to_string(t) << "\n";
 }
Referenced by main().
requires() [1/3]
template<typename T > requires (is_vector< T >||is_list< T >)
Definition at line 52 of file print_ip.h.
{
     size_t i{1};
     std::string result;
     for(const auto& element: t) {
         result.append(std::to_string(element));
         if (i++ != t.size()) result.append(".");
     }
     return result;
 }
requires() [2/3]
template<typename T > requires (std::integral< T >)
Definition at line 15 of file print_ip.h.
{
     std::vector<std::string> addr = {};
     for (auto i = sizeof (t); i > 0; --i) {
         addr.emplace_back(std::to_string(static_cast<int16_t>(t & 0xFF)));
         t /= 256;
         addr.emplace_back(".");
     }
     addr.pop_back();
     std::string result;
     for(const auto& element: std::ranges::reverse_view{addr})
         result.append(element);
     return result;
 }
requires() [3/3]
template<typename T > requires (std::is_convertible_v< T, std::string_view >)
Definition at line 33 of file print_ip.h.
{
     return std::string{t};
 }
to_string()
template<typename T > std::string to_string (T t)
Definition at line 116 of file print_ip.h.
                                             {  // Печать std::tuple c элементами одного типа
     if constexpr (std::tuple_size_v<T> != 0) { // компиляция не должна падать при пустом std::tuple
         return tuple_print<0>(t);
     }
     return std::string{""};
 }
Referenced by print_ip(), requires(), TEST(), and tuple_print().
tuple_print()
template<size_t i, typename... T> std::string tuple_print (const std::tuple< T... > & t)
Definition at line 95 of file print_ip.h.
{
     std::string result;
     result.append(std::to_string(get<i>(t)));
     if constexpr((i+1) != std::tuple_size_v<std::tuple<T...>>)
         result.append(".");
     if constexpr((i+1) < std::tuple_size_v<std::tuple<T...>>)
         result.append(tuple_print<i+1>(t));
     return result;
 }
Variable Documentation
is_list
template<typename T > concept is_list = std::same_as<std::decay_t<T>, std::list<typename std::decay_t<T>::value_type> >
Check T is std::list.
Template Parameters
T template parameter
Definition at line 50 of file print_ip.h.
is_tup
template<typename T > concept is_tup = is_tuple_of_same_types<T>::value
Check T is std::tuple with one type elements.
Template Parameters
T template parameter
Definition at line 113 of file print_ip.h.
is_vector
template<typename T > concept is_vector = std::same_as<std::decay_t<T>, std::vector<typename std::decay_t<T>::value_type> >
Check T is std::vector.
Template Parameters
T template parameter
Definition at line 43 of file print_ip.h.