name: 'Home Work 4 doc'

on:
  push:
    branches:
      - homework_04
      - feature/github_actions
  workflow_dispatch:

jobs:
  generate:
    runs-on: ubuntu-latest
    permissions: write-all
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: "true"
      - run: sudo apt-get install doxygen graphviz -y
      - run: doxygen Doxyfile
      - uses: JamesIves/github-pages-deploy-action@v4.4.3
        with:
          branch: "homework_04_doc"
          folder: "doc"